require 'finan'

CASHFLOW = {
  -10000.00,
    1500.00,
    1500.00,
    1500.00,
    1500.00,
    1500.00,
    1500.00,
    1500.00,
    1500.00,
    1500.00,
    1500.00,
    1500.00,
    1500.00
}

SIZE = #CASHFLOW
  
io.write("Internal rate of return (rate) .....: ")
print(fmt("%8.6f", irr(CASHFLOW, SIZE)))
io.write("Internal rate of return (percent) ..: ")
print(fmt("%4.2f", irr(CASHFLOW, SIZE) * 100) .. "%")

print()
io.write("Press <Enter> to finish...")
io.read '*l'

-- Calculates the internal rate of return for a series os cash flow 
-- values generated by an investment.
--
-- Suppose you want to calculate the internal rate of return of a 
-- $ 10,000 investment that is followed by 12 monthly payments $ 1,500.
-- Using a guess of 12%. (LOTUS, 1991)
--
-- Result = 0.104482 or 10.45%
-- Accuracy up to 6 decimal places.
--
-- LOTUS. @Functions and Macros Guide: Lotus 1-2-3 release 2.3.
-- Cambridge: Lotus Development Corporation, 1991.
